[tool.poetry]
name = "sfac-gpt-label"
version = "0.1.0"
description = ""
authors = ["John Shaffer <john@insilica.co>"]

[tool.poetry.dependencies]
python = "^3.10"
llama-index = "^0.4.27"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
